-- 사용자 정보를 저장하는 테이블
/*
    사용자번호,
    사용자아이디, 
    사용자비밀번호,
    사용자이름,
    사용자이메일,
    사용자연락처,
    사용자탈퇴여부,
    정보변경일자
    등록일자
*/

CREATE TABLE COMM_USERS (
    USER_NO NUMBER(4),
    USER_ID VARCHAR2(255) NOT NULL,
    USER_PASSWORD VARCHAR2(255) NOT NULL,
    USER_NAME VARCHAR2(255) NOT NULL,
    USER_EMAIL VARCHAR2(255),
    USER_TEL VARCHAR2(255),
    USER_DELETED CHAR(1) DEFAULT 'N',
    USER_UPDATED_DATE DATE DEFAULT SYSDATE,
    USER_CREATED_DATE DATE DEFAULT SYSDATE,
    
    CONSTRAINT USERS_NO_PK PRIMARY KEY (USER_NO),
    CONSTRAINT USERS_ID_UK UNIQUE (USER_ID),
    CONSTRAINT USERS_EMAIL_UK UNIQUE (USER_EMAIL)
);

-- 사용자 번호용 시퀀스
CREATE SEQUENCE USERS_SEQ START WITH 1000 NOCACHE;
